import { Mail } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { useState } from "react";

export default function Emails() {
  const [selectedEmail, setSelectedEmail] = useState<string | null>(null);
  
  const mockEmails = [
    {
      id: "1",
      supplier: "TechParts Global",
      subject: "Partnership Inquiry - Electronics Components",
      status: "draft",
      preview: "Dear TechParts Global Team, We are reaching out regarding a procurement opportunity...",
      fullContent: `Dear TechParts Global Team,

We are reaching out regarding a procurement opportunity for electronics components. Our company is currently seeking reliable suppliers for the following items:

- Circuit boards (various specifications)
- Semiconductor components
- Electronic connectors and cables
- Power supply units

We would like to discuss:
1. Your current product catalog and availability
2. Pricing structure for bulk orders (1000+ units)
3. Lead times and shipping options
4. Quality certifications and compliance standards

Please let us know your availability for a call next week to discuss this opportunity in detail.

Best regards,
Procurement Team`,
    },
    {
      id: "2",
      supplier: "Asia Components Ltd",
      subject: "Partnership Inquiry - Electronics Components",
      status: "approved",
      preview: "Dear Asia Components Ltd Team, We are reaching out regarding a procurement opportunity...",
      fullContent: `Dear Asia Components Ltd Team,

We are reaching out regarding a procurement opportunity for electronics components. After reviewing your company profile and capabilities, we believe there may be a strong partnership opportunity.

Our requirements include:
- High-quality electronic components with ISO certification
- Flexible order quantities (starting at 500 units)
- Competitive pricing with volume discounts
- Reliable shipping to North America

We are particularly interested in:
• Microcontrollers and processors
• Passive components (resistors, capacitors)
• LED components and displays
• Sensor modules

Could we schedule a call to discuss potential collaboration? We're available Monday-Friday, 9 AM - 5 PM EST.

Looking forward to your response.

Best regards,
Procurement Team`,
    },
  ];

  const getStatusBadge = (status: string) => {
    return status === "approved" ? (
      <Badge>Approved</Badge>
    ) : (
      <Badge variant="outline">Draft</Badge>
    );
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Mail className="h-6 w-6 text-primary" />
            <div>
              <CardTitle>Email Drafts</CardTitle>
              <CardDescription>
                Review and manage outreach emails generated by the Communicator agent
              </CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {mockEmails.length === 0 ? (
              <div className="text-center py-12">
                <Mail className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
                <p className="text-muted-foreground">
                  No email drafts yet. Start a task and approve suppliers to generate emails.
                </p>
              </div>
            ) : (
              mockEmails.map((email) => (
                <div key={email.id} className="p-6 rounded-lg border bg-card space-y-3">
                  <div className="flex items-start justify-between">
                    <div>
                      <h3 className="font-semibold text-lg">{email.supplier}</h3>
                      <p className="text-sm text-muted-foreground">{email.subject}</p>
                    </div>
                    {getStatusBadge(email.status)}
                  </div>
                  <p className="text-sm text-muted-foreground line-clamp-2">
                    {email.preview}
                  </p>
                  <div className="flex gap-2">
                    <Dialog>
                      <DialogTrigger asChild>
                        <Button size="sm" variant="outline">
                          View Full Email
                        </Button>
                      </DialogTrigger>
                      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
                        <DialogHeader>
                          <DialogTitle>{email.supplier}</DialogTitle>
                          <DialogDescription>{email.subject}</DialogDescription>
                        </DialogHeader>
                        <div className="mt-4 space-y-4">
                          <div className="whitespace-pre-wrap text-sm leading-relaxed">
                            {email.fullContent}
                          </div>
                          <div className="flex gap-2 pt-4 border-t">
                            {email.status === "draft" && (
                              <Button size="sm">Mark Approved</Button>
                            )}
                            <Button size="sm" variant="outline">Copy to Clipboard</Button>
                          </div>
                        </div>
                      </DialogContent>
                    </Dialog>
                    {email.status === "draft" && (
                      <Button size="sm">Mark Approved</Button>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>
        </CardContent>
      </Card>

      <Card className="bg-muted/50">
        <CardContent className="pt-6">
          <p className="text-sm text-muted-foreground">
            💡 <strong>Note:</strong> In production, approved emails would be sent via your 
            CRM/email integration (e.g., SendGrid, Mailgun, or direct SMTP).
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
